name: PHPUnit Tests
on: [push]
jobs:
  Run-Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        with:
          php-version: '8.0'
          tools: 'composer'
        run: composer install
      - name: Run tests
        run: vendor/bin/phpunit