name: PHPUnit Tests
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    with:
      php-version: '8.0'
      tools: 'composer'
    steps:
      - run: composer install
      - run: vendor/bin/phpunit